site_name: 'OpenStudio<sup>&reg;</sup> SDK User Docs'
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]

- [getting_started/features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Planned Features]
- [getting_started/getting_started.md, Getting Started, Installation and Introductory Tutorial]
- [getting_started/about_measures.md, Getting Started, About Measures]


- [reference/model_objects.md, Reference, OpenStudio Model Objects Overview]
- [reference/command_line_interface.md, Reference, Command Line Interface]
- [reference/tutorial_bcl.md, Reference, Building Component Library]
- [reference/parametric_analysis_tool_2.md, Reference, Parametric Analysis Tool (PAT) Interface Guide]
- [reference/openstudio_results_measure.md, Reference, OpenStudio Results Measure]
- [reference/measure_writing_guide.md, Reference, Measure Writer's Reference Guide]
- [reference/measure_code_examples.md, Reference, Measure Code Examples]
- [reference/developing_measure_collections.md, Reference, Developing Measure Collections]
- [reference/geometry_editor.md, Reference, FloorspaceJS]
- [reference/life_cycle_costing_examples.md, Reference, Life Cycle Cost Analysis]
- [reference/refguide_radiance.md, Reference, OpenStudio-Radiance Reference Guide]

- [help/best_practices.md, Help, Modeling Best Practices]
- [help/finding_model_data.md, Help, Finding Model Data]
- [help/training.md, Help, Find Training]
- [help/software_license.md, Help, Software License]

theme: simplex
theme_dir: 'bootstrap_nrel'



