site_name: 'OpenStudio<sup>&reg;</sup> User Docs'
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]

- [getting_started/features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Planned Features]
- [getting_started/getting_started.md, Getting Started, Installation and Introductory Tutorial]
- [getting_started/quick_start_guides.md, Getting Started, Quick Start Guides]
- [getting_started/about_measures.md, Getting Started, About Measures]

- [tutorials/large_scale_analysis.md, Essential Tutorials, Large Scale Analysis]
- [tutorials/tutorial_bcl.md, Essential Tutorials, Building Component Library]

- [tutorials/utility_rate_tariffs.md, Advanced Tutorials, Utiity Rate Tariffs]
- [tutorials/life_cycle_costing_examples.md, Advanced Tutorials, Life Cycle Cost Analysis]
- [tutorials/tutorial_gbxmlimport.md, Advanced Tutorials, Import gbXML]
- [tutorials/tutorial_shadingcontrols.md, Advanced Tutorials, Shading Controls]
- [tutorials/tutorial_windowproperty_frameanddivider.md, Advanced Tutorials, Window Property Frame and Divider]

- [reference/geometry_editor.md, Reference, FloorspaceJS]
- [reference/command_line_interface.md, Reference, Command Line Interface]
- [reference/parametric_studies.md, Reference, Parametric Analysis Tool (PAT) Interface Guide]
- [reference/parametric_analysis_tool_2.md, Reference, Parametric Analysis Tool Version 2 (PAT) Interface Guide]
- [reference/model_objects.md, Reference, OpenStudio Model Objects Overview]
- [reference/measure_writing_guide.md, Reference, Measure Writer's Reference Guide]
- [reference/measure_code_examples.md, Reference, Measure Code Examples]
- [reference/developing_measure_collections.md, Reference, Developing Measure Collections]
- [reference/refguide_radiance.md, Reference, OpenStudio-Radiance Reference Guide]
- [reference/openstudio_results_measure.md, Reference, OpenStudio Results Measure]

- [help/training.md, Help, Find Training]
- [help/best_practices.md, Help, Modeling Best Practices]
- [help/software_license.md, Help, Software License]

theme: simplex
theme_dir: 'bootstrap_nrel'



