site_name: OpenStudio User Docs
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]
- [getting_started/features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Features Roadmap]
- [getting_started/getting_started.md, Getting Started, Installation and Introductory Tutorial]
- [next_steps/sketchup_plugin_interface.md, References & Tutorials, SketchUp Plug-in Interface]
- [next_steps/openstudio_application_interface.md, References & Tutorials, OpenStudio Application Interface]
- [next_steps/model_objects.md, References & Tutorials, Overview of OpenStudio Model Objects]
- [next_steps/creating_your_model.md, References & Tutorials, Creating Your Model]
- [next_steps/running_your_simulation.md, References & Tutorials, Running Your Simulation & Viewing Results]
- [next_steps/detailed_tutorials/tutorial_glhepro.md, References & Tutorials, GLHEPro Tutorial]
- [measures/about_measures.md, Measures, About Measures]
- [measures/measure_writing_guide.md, Measures, Measure Writing Guide]
- [comparative_analysis/parametric_studies.md, Comparative Analysis, ParametricAnalysisTool]
- [comparative_analysis/large_scale_analysis.md, Comparative Analysis, Large Scale Analysis]
- [help/training.md, Help, Training]
- [help/finding_model_data.md, Help, Finding Model Data]
- [help/best_practices.md, Help, Best Practices]
- [help/troubleshooting.md, Help, Troubleshooting]
- [help/faq.md, Help, FAQ]

theme_dir: 'bootstrap_nrel'



