site_name: OpenStudio User Docs
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]
- [getting_started/Features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Features Roadmap]
- [getting_started/GettingStarted.md, Getting Started, Installation and Introductory Tutorial]
- [next_steps/sketchup_plugin_interface.md, References & Tutorials, SketchUp Plug-in Interface]
- [next_steps/openstudio_application_interface.md, References & Tutorials, OpenStudio Application Interface]
- [next_steps/model_objects.md, References & Tutorials, Overview of OpenStudio Model Objects]
- [next_steps/CreatingYourModel.md, References & Tutorials, Creating Your Model]
- [next_steps/RunningYourSimulation.md, References & Tutorials, Running Your Simulation & Viewing Results]
- [next_steps/detailed_tutorials/tutorial_glhepro.md, References & Tutorials, GLHEPro Tutorial]
- [measures/AboutMeasures.md, Measures, About Measures]
- [measures/Measure-Writing-Guide.md, Measures, Measure Writing Guide]
- [comparative_analysis/ParametricStudies.md, Comparative Analysis, ParametricAnalysisTool]
- [comparative_analysis/LargeScaleAnalysis.md, Comparative Analysis, Large Scale Analysis]
- [help/Training.md, Help, Training]
- [help/FindingModelData.md, Help, Finding Model Data]
- [help/BestPractices.md, Help, Best Practices]
- [help/Troubleshooting.md, Help, Troubleshooting]
- [help/FAQ.md, Help, FAQ]

theme_dir: 'bootstrap_nrel'



