site_name: OpenStudio User Docs
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]

- [getting_started/features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Planned Features]
- [getting_started/getting_started.md, Getting Started, Installation and Introductory Tutorial]
- [getting_started/quick_start_guides.md, Getting Started, Quick Start Guides]
- [getting_started/about_measures.md, Getting Started, About Measures]

- [tutorials/creating_your_model.md, Tutorials, Creating a Model]
- [tutorials/running_your_simulation.md, Tutorials, Running Simulations & Viewing Results]
- [tutorials/life_cycle_costing_examples.md, Tutorials, Life Cycle Costing Examples]
- [tutorials/tutorial_cbecc_materials.md, Tutorials, CBECC Materials Tutorial]
- [tutorials/tutorial_glhepro.md, Tutorials, GLHEPro Tutorial]
- [tutorials/tutorial_shadingcontrols.md, Tutorials, Shading Controls Tutorial]
- [tutorials/tutorial_windowproperty_frameanddivider.md, Tutorials, Window Property Frame and Divider Tutorial]
- [tutorials/large_scale_analysis.md, Tutorials, Large Scale Analysis]
- [tutorials/radiance_tutorial.md, Tutorials, Using Radiance with OpenStudio]

- [reference/openstudio_application_interface.md, Reference, OpenStudio Application Interface Guide]
- [reference/sketchup_plugin_interface.md, Reference, SketchUp Plug-in Interface Guide]
- [reference/parametric_studies.md, Reference, Parametric Analysis Tool (PAT) Interface Guide]
- [reference/model_objects.md, Reference, OpenStudio Model Objects Overview]
- [reference/measure_writing_guide.md, Reference, Measure Writing Guide]
- [reference/measure_code_examples.md, Reference, Measure Code Examples]
- [reference/refguide_radiance.md, Reference, OpenStudio-Radiance Reference Guide]

- [help/training.md, Help, Find Training]
- [help/finding_model_data.md, Help, Finding Model Data]
- [help/best_practices.md, Help, Modeling Best Practices]
- [help/troubleshooting.md, Help, Troubleshooting]
- [help/faq.md, Help, FAQ]
- [help/software_license.md, Help, Software License]

theme: simplex
theme_dir: 'bootstrap_nrel'



