site_name: OpenStudio User Docs
site_favicon: favicon.ico
site_logo: 'OS_32x32.png'

pages:
- [index.md]
- [getting_started/features.md, Getting Started, Current Features]
- [getting_started/roadmap.md, Getting Started, Planned Features]
- [getting_started/getting_started.md, Getting Started, Installation and Introductory Tutorial]
- [next_steps/quick_start_guides.md, Tutorials, Quick Start Guides]
- [next_steps/sketchup_plugin_interface.md, Tutorials, SketchUp Plug-in]
- [next_steps/openstudio_application_interface.md, Tutorials, OpenStudio Application]
- [next_steps/model_objects.md, Tutorials, Overview of OpenStudio Model Objects]
- [next_steps/creating_your_model.md, Tutorials, Creating Your Model]
- [next_steps/running_your_simulation.md, Tutorials, Running Your Simulation & Viewing Results]
- [next_steps/life_cycle_costing_examples.md, Tutorials, Life Cycle Costing Examples]
- [next_steps/detailed_tutorials/tutorial_cbecc_materials.md, Tutorials, CBECC Materials Tutorial]
- [next_steps/detailed_tutorials/tutorial_glhepro.md, Tutorials, GLHEPro Tutorial]
- [next_steps/detailed_tutorials/tutorial_shadingcontrols.md, Tutorials, Shading Controls Tutorial]
- [next_steps/detailed_tutorials/tutorial_windowproperty_frameanddivider.md, Tutorials, Window Property Frame and Divider Tutorial]
- [tutorials/tutorial_radiance.md, Tutorials, Radiance Daylighting Tutorial]
- [measures/about_measures.md, Measures, About Measures]
- [measures/measure_writing_guide.md, Measures, Measure Writing Guide]
- [measures/measure_code_examples.md, Measures, Measure Code Examples]
- [comparative_analysis/parametric_studies.md, Comparative Analysis, ParametricAnalysisTool]
- [comparative_analysis/large_scale_analysis.md, Comparative Analysis, Large Scale Analysis]
- [reference/refguide_radiance.md, Reference Guides, OpenStudio-Radiance Reference Guide]
- [help/training.md, Help, Training]
- [help/finding_model_data.md, Help, Finding Model Data]
- [help/best_practices.md, Help, Best Practices]
- [help/troubleshooting.md, Help, Troubleshooting]
- [help/faq.md, Help, FAQ]
- [help/software_license.md, Help, Software License]

theme: simplex
theme_dir: 'bootstrap_nrel'



